# Generated by Django 4.2 on 2024-12-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('Available', 'Disponible'), ('Soon', 'Proximamente'), ('Not Available', 'No Disponible')], max_length=20),
        ),
    ]
