# Generated by Django 4.2 on 2024-12-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('Not Available', 'No Disponible'), ('Soon', 'Proximamente'), ('Available', 'Disponible')], max_length=20),
        ),
    ]
