# Generated by Django 4.2 on 2025-01-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complete_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
