# Generated by Django 4.2 on 2025-01-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_cartitem_productsize_remove_product_price_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='name',
            new_name='size',
        ),
    ]
