# Generated by Django 4.2 on 2025-01-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
