# Generated by Django 4.2 on 2025-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('Available', 'Disponible'), ('Not Available', 'No Disponible'), ('Soon', 'Proximamente'), ('Special', 'Producto Especial')], max_length=20),
        ),
    ]
